package com.ApiTiendaPeliculas.Entity;

import java.io.Serializable;
import java.sql.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name="PELICULAS")
public class Peliculas implements Serializable{

	/*
CREATE TABLE PELICULAS (
ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,--AUTOINCREMENTABLE
NOMBRE VARCHAR2(80) NOT NULL,
PRECIO NUMBER NOT NULL,
FECHA_LANZ DATE,
GENERO VARCHAR2(70) NOT NULL
);*/
	
	@Id
	@Column(name="ID",columnDefinition = "NUMBER",nullable = false)
	Long idP;
	
	@Column(name="NOMBRE")
	String nombre;
	
	@Column(name="PRECIO")
	Float precio;
	
	@Column(name="FECHA_LANZ")
	Date fechaLanz;
	
	@Column(name="GENERO")
	String genero;

	public Peliculas(Long idP, String nombre, Float precio, Date fechaLanz, String genero) {
		this.idP = idP;
		this.nombre = nombre;
		this.precio = precio;
		this.fechaLanz = fechaLanz;
		this.genero = genero;
	}

	public Peliculas() {
	}

	@Override
	public String toString() {
		return "Peliculas [idP=" + idP + ", nombre=" + nombre + ", precio=" + precio + ", fechaLanz=" + fechaLanz
				+ ", genero=" + genero + "]\n";
	}

	public Long getIdP() {
		return idP;
	}

	public void setIdP(Long idP) {
		this.idP = idP;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Float getPrecio() {
		return precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	public Date getFechaLanz() {
		return fechaLanz;
	}

	public void setFechaLanz(Date fechaLanz) {
		this.fechaLanz = fechaLanz;
	}

	public String getGenero() {
		return genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}


	
}
